### PR TITLE
feat: connect new data source

### PR DESCRIPTION
**Pull request by gjcochran**
## Overview

Finished version 1 of the create data sources page. Allows a user of the web app to connect an existing Kinesis Stream to a ClickHouse database table.

## Changes

- We chose to use the `useContext` hook to share state between parent and child components for `streamName`, `integrationName` (ie tableName), and `finalizedSchema`
- We provided typing for all components with zod (thank you Tony for the suggestion!)

#### Backend team: We ran into issues using several of the backend API routes.
1.  `/api/kinesis-sample`
It was unexpectedly returning an error response, when we were passing in the correct arguments. We believe the issue is with the shard logic:

 ```python
shard_iterator = kinesis_client.get_shard_iterator(
      StreamName=stream_name,
      ShardId='shardId-000000000001',  # Assume single shard for simplicity
      ShardIteratorType='LATEST'
      )['ShardIterator']
```

2. `/api/authenticate`
Error handling if no credentials are submitted. It will default to using the default user defined in the local machine's `~/.aws/credentials`
To discuss: We could provide error handling on front end for this as well, in which case there may be no need to adjust the backend code.

#### Outstanding to do items:
1. Finish `DataSourceConfirmation` component, specifically functionality to let a user navigate the newly created table in the SQL Console page
2. For any map iteration, creating unique React key props
3. Handling error state and providing user with error messsages
4. Updating services functions for `/api/databases` and `/api/query` with zod typing

### CODE REVIEW

**Comment by bspowell** [comment]
To your point on #1: "It was unexpectedly returning an error response, when we were passing in the correct arguments. We believe the issue is with the shard logic"
- The reason this wasn't working is because you needed to have the python generator script running to stream events into the kinesis stream. Our logic uses the LATEST ShardInteratorType and we need to have events streaming for it to find the latest event. 
- We can have an assumption that the client needs to have active streaming data within their streams in order to connect to the stream itself.

**Comment by gjcochran** [comment]
Thanks for looking into that, Sean! You are correct that we were not actively streaming events to our Kinesis stream when testing our React code... Realistically, users' Kinesis streams will be continuously receiving streaming data so we should be okay with our backend code to maintain that assumption and search for events based on the 'Latest' offset. We may want to consider a future feature providing the user the option to view a sample event based on a different offset.

**Comment by bspowell** [comment]
Exactly what we were thinking re: continuously streaming data. Also good point regarding the different offset, we can add that to future considerations. 

Otherwise all code you both did looks good!

**Review by bspowell — APPROVED** [review]

**Review by Kuanchiliao1 — APPROVED** [review]
Looks great!

**Pull request merged**
